# Generated by Django 4.2.7 on 2024-01-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MassageChair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('description', models.TextField(default=None)),
                ('type', models.CharField(choices=[('recliners', 'Recliners'), ('air_massage', 'Air Massage')], default=('recliners', 'Recliners'), max_length=35)),
            ],
        ),
    ]
