# Generated by Django 4.2.7 on 2024-01-27 16:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20)),
                ('authorized_in', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChairFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ChairType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Color_Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50, unique=True)),
                ('color_code', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Chair Colors',
            },
        ),
        migrations.RemoveField(
            model_name='massagechair',
            name='type',
        ),
        migrations.AddField(
            model_name='massagechair',
            name='brand',
            field=models.CharField(choices=[('kahuna', 'Kahuna'), ('osaki', 'Osaki'), ('real_relax', 'real Relax')], default=('kahuna', 'Kahuna'), max_length=35),
        ),
        migrations.AddField(
            model_name='massagechair',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='massagechair',
            name='purchased',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='massagechair',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.6, max_digits=2, validators=[django.core.validators.MaxValueValidator(limit_value=5.0)]),
        ),
        migrations.AlterField(
            model_name='massagechair',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='ChairComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(default='Anonymous', max_length=35)),
                ('comment_text', models.TextField(default=None)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('posted_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soothestore.massagechair')),
            ],
        ),
        migrations.AddField(
            model_name='massagechair',
            name='available_colors',
            field=models.ManyToManyField(related_name='massage_chairs', to='soothestore.color_options'),
        ),
        migrations.AddField(
            model_name='massagechair',
            name='features',
            field=models.ManyToManyField(related_name='Massage_Features', to='soothestore.chairfeature'),
        ),
    ]
