# Generated by Django 4.2.7 on 2024-01-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0002_alter_massagechair_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='massagechair',
            name='purchased',
            field=models.IntegerField(default=0),
        ),
    ]
