# Generated by Django 4.2.7 on 2024-01-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0003_alter_massagechair_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massagechair',
            name='posted',
        ),
    ]
