# Generated by Django 4.2.7 on 2024-01-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0003_massagechair_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='massagechair',
            name='product_rating',
            field=models.FloatField(default=4.6, max_length=5),
        ),
    ]
