# Generated by Django 4.2.7 on 2024-01-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0004_massagechair_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massagechair',
            name='product_rating',
            field=models.DecimalField(decimal_places=1, default=4.6, max_digits=2),
        ),
    ]
