# Generated by Django 4.2.7 on 2024-02-14 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0004_remove_massagechair_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massagechair',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='soothestore.brand'),
        ),
    ]
