# Generated by Django 4.2.7 on 2024-01-22 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0005_alter_massagechair_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massagechair',
            name='product_rating',
        ),
        migrations.AddField(
            model_name='massagechair',
            name='brand',
            field=models.CharField(choices=[('recliners', 'Recliners'), ('air_massage', 'Air Massage')], default=('recliners', 'Recliners'), max_length=35),
        ),
        migrations.AddField(
            model_name='massagechair',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.6, max_digits=2, validators=[django.core.validators.MaxValueValidator(limit_value=5.0)]),
        ),
    ]
