# Generated by Django 4.2.7 on 2024-01-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0008_chairfeature_rename_date_chaircomment_posted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChairType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called', models.CharField(max_length=60)),
            ],
        ),
    ]
